### PR TITLE
add pytest-qt

### PR DESCRIPTION
**Pull request by caiopeternela**
support for creating tests using [pytest-qt](https://pytest-qt.readthedocs.io/en/latest) and a basic test as an example

@ogkalu2 do you think that makes sense?

### CODE REVIEW

**Comment by ogkalu2** [comment]
@caiopeternela 
Good Idea. Thanks for this. Before i merge, Are you also planning on writing actual tests ?

**Comment by caiopeternela** [comment]
yup, just trying to get a little more context before that

**Comment by caiopeternela** [comment]
> @caiopeternela 
> Good Idea. Thanks for this. Are you also planning on writing actual tests ?

yup, just trying to get a little more context before that

**Comment by ogkalu2** [comment]
@caiopeternela Alright Thanks.

**Pull request merged**
